### ISSUE TITLE
URL is not a constructor at Gaxios.validateOpts

### ISSUE THREAD

**Issue by dmytrobanasko** [JustinBeckwith/gaxios#44]
It looks like after migration from axios to gaxios in googleapis v37.0.0 [feat: make it webpackable](https://github.com/googleapis/google-auth-library-nodejs/pull/371) feature does not work properly. 
Build with webpack works fine but getting an error on any request: `URL is not a constructor at Gaxios.validateOpts` [gaxios.ts#L151](https://github.com/JustinBeckwith/gaxios/blob/6c66e4377d7bfa455859d3b6021c9e7d1167133c/src/gaxios.ts#L151)
Node URL Api is incompatible with node-url in webpack's lib. Some details can be found here: 
https://github.com/webpack/node-libs-browser/issues/69
https://github.com/webpack/node-libs-browser/issues/78

Is it supposed to be used with webpack ?

@alexander-fenster

**Comment by alexander-fenster** [comment]
I checked the basic usage of webpacked libraries before we released v37.0.0 and it worked, but let me double check - until we're covered by some real tests, it's very possible we could break something without even noticing. Tests for browser stuff is WIP.

We are not planning to use any polyfills for `url` module, `window.URL` works just great for our purposes. It seems that gaxios has no idea (yet) that it should use `window.URL`, not the `url` module. If my understanding is correct here I'll try to fix it now.

**Comment by alexander-fenster** [comment]
Thanks @dmytrobanasko - I was able to repro that, #45 should fix the problem.

**Comment by dmytrobanasko** [comment]
That was fast =] Thank you!

**Comment by vc102375** [comment]
I am still facing this issue on lambda when  i run google translate api's... 

2019-03-05T18:32:45.289Z	5b2767e6-8af1-47b1-9b50-86ef389b2b78	TypeError: URL is not a constructor
at Gaxios.validateOpts (/var/task/node_modules/gaxios/build/src/gaxios.js:125:27)
at Gaxios.<anonymous> (/var/task/node_modules/gaxios/build/src/gaxios.js:60:25)
at next (native)
at /var/task/node_modules/gaxios/build/src/gaxios.js:19:71
at __awaiter (/var/task/node_modules/gaxios/build/src/gaxios.js:15:12)
at Gaxios.request (/var/task/node_modules/gaxios/build/src/gaxios.js:59:16)
at Object.<anonymous> (/var/task/node_modules/gaxios/build/src/index.js:38:33)
at next (native)
at /var/task/node_modules/gaxios/build/src/index.js:19:71
at __awaiter (/var/task/node_modules/gaxios/build/src/index.js:15:12)

**Comment by alexander-fenster** [comment]
@vc102375 How exactly are you using the code? Is it a regular Node.js application - if so, which Node.js version is used?

**Comment by alexander-fenster** [comment]
@vc102375 A wild guess: is there any chance that you have a global variable named `window` defined somewhere? What does 'console.log(typeof window);` print in your code?

**Comment by vc102375** [comment]
using Node 6.10 , i am calling google translate api's thats all I am doing not calling  gaxios directly . all was fine until 14 hours ago when redeployed the api on lambda to fix a issue. 

yield translate.translate(text, options)
		.then(results => {
			console.log(results)
			const translation = results[0];
			return translation;
		})
		.catch(err => {
			console.error('ERROR:', err);
			return false
		});

**Comment by stephenplusplus** [comment]
This is tracking this issue: https://github.com/JustinBeckwith/gaxios/issues/54

**Comment by alexander-fenster** [comment]
@vc102375 Oh, that's bad. `URL` class was added in v6.13.0. The easiest way for you is switching to Node.js v8 since v6 will be EOL in less than a month. 

As a quick workaround, you can add this to the very beginning of the your application:

```js
const url = require('url'); // legacy Node6 url
const semver = require('semver');
class Node6CompatibilityURL {
  constructor(str) {
    this.url = url.parse(str);
    this.origin = this.url.protocol + '//';
    this.pathname = this.url.pathname ? this.url.pathname : '';
    this.search = this.url.search ? this.url.search : '';
    this.href = this.url.href ? this.url.href : '';
  }
}

if (semver.lt(process.version, '6.13.0')) {
  window = {};
  window.URL = Node6CompatibilityURL; // no warranty 😱 
}
```

Make sure you `npm install semver` to make it work. This code creates a global `window` object with `window.URL` that will make gaxios think it's running in browser mode, so it will use this instead of the URL class that will appear in v6.13.0. Thanks for `semver` check, it will keep working even after you upgrade Node.js. Please try that and let me know if it helped.
